version: '3'

vars:
  TERRAFORM_DIR: "terraform"

tasks:
  init-plan:
    desc: "Plan resource provisioning with terraform"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform init 
      - terraform validate
      - terraform fmt
      - terraform plan -var-file=dev.tfvars

  deploy:
    desc: "Provision all the resources"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform apply -var-file=dev.tfvars -auto-approve
    depends: ['terraform-plan']

  delete:
    desc: "Clean up all the resources"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform destroy -var-file=dev.tfvars -auto-approve
    depends: ['terraform-plan']

